### ISSUE TITLE
Weather Unsynced

### ISSUE THREAD

**Issue by NekoIceshard** [ANormalTwig/LC-LateCompany#18]
So the issue me and my friend ran into it when we were testing mods, we tried the late join, and on the standard world, his game was showing normal conditions with no weather. where when i joined, my side was flooding. he could hear when i was under water but would be standing right beside me and have no issues and sounded normal.

I don't really have a step my step to reproduce, it just happened when i joined his world after he had landed.

Just looking to see if you're able to get the weather of the world to sync up, perhaps its a seed issue?

sadly i didn't take any screen shots.

nest regards, Neko

**Comment by Hexus-One** [comment]
Do you both have the mod installed or just the host?

**Comment by Chimantha** [comment]
Hi, I'm also experiencing this issue. After an hour of testing I'm 100% that it's late company causing the issue.  IT's also in situations where it wouldn't really make sense for late company to like really kick in since I've been testing with one other person who is joining before the lobby is started.
It's making the mod unusable since we'll arrive at a flooded March and every player in the lobby has the map at full flood levels. Which now that I think about it, I guess I wouldn't describe it as the weather being unsynced, more so just wrong.
Bless, hope you can get this worked out.

**Comment by NilaierMusic** [comment]
Yeah, this also happens with rainy weather, where quick sand is not in the same position for host and client even if both have the mod. Happens in Online and LAN.

**Comment by RhysxOshea** [comment]
Happens to me aswell, I had no weather and my teammates had lightning, and when I did a solo game, it had fog instead of stormy

**Comment by Krampus69** [comment]
Same here, here is a video to show the issue : 
https://streamable.com/vdnvkl
