### ISSUE TITLE
Not able to invite or join mid session

### ISSUE THREAD

**Issue by JGration** [ANormalTwig/LC-LateCompany#22]
**Describe the bug**
I've been using late company for a while but ever since the last update it hasn't been working.

**To Reproduce**
1. Start lobby.
2. Begin first expedition.
3. Play a mission or two.
4. Try to invite other players in missions.

**Expected behavior**
Should be able to invite or players should be able to join. On a previous version this worked.

**Additional context**
Current mods: MoreCompany, LateCompany, Skinwalker, HelmetCamera

**Comment by Dhogins** [comment]
Same problem here

**Comment by anormaltwig** [comment]
MoreCompany is likely to conflict, by default players can only join while the ship is in orbit.

**Comment by Buckminsterfullerene02** [comment]
I am using MoreCompany and LateCompany with my mates and we had the same issue.

After a little digging, it seems that the mod has a config file in `BepInEx\config\twig.latecompany.cfg` that contains a bool called `Allow joining while landed` and is set to `false` by default.

**By setting this value to `true`, the mod works for us fine.** 

However the comment above does state that setting it to true may break some things, so we'll have to see what.

We didn't test to see if the mod works when this setting is false while the ship is not landed, but if it does work, then it seems to be that the purpose of this mod is to remove the need for the server restart to get a new player in when the ship is not landed. Rather than what you would *think* is the purpose of it where it would actually allow players to join when the ship is landed.

**Comment by NoPurposeInLife** [comment]
For those finding the config file, if you're using r2modman, it's in:

r2modman -> config editor (left side) -> BepInEx\config\twig.latecompany.cfg -> Allow Joining while landed -> True -> Save

**Comment by Buckminsterfullerene02** [comment]
I've been using this config set to true for a few hours of gameplay with my mates and we've not noticed any changes/breakages in how the game runs so I think it's safe to use. Could be set to true by default perhaps?
